=== FutureElement/FEEP/src/main/resources/FeepResource/scheme/Feep-1.0.xsd
<?xml version="1.0" encoding= "UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.feep.com/schema" targetNamespace="http://www.feep.com/schema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="FEEP">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="Constant">
					<xsd:complexType>
						<xsd:sequence>
                            <xsd:element name="Title" type="xsd:string" />
                            <xsd:element name="ContextPath" type="xsd:string" />
							<xsd:element name="DevMode" type="xsd:boolean" />
							<xsd:element name="Temp" type="xsd:string" />
							<xsd:element name="DefaultPageSize" type="xsd:string" />
							<xsd:element name="AddUserToCache" type="xsd:string" />
						</xsd:sequence>
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="FileUpload">
					<xsd:complexType>
						<xsd:sequence></xsd:sequence>
						<xsd:attribute name="maxUploadSize" type="xsd:string" />
						<xsd:attribute name="maxInMemorySize" type="xsd:string" />
						<xsd:attribute name="uploadPath" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="DataSource">
					<xsd:complexType>
						<xsd:sequence></xsd:sequence>
						<xsd:attribute name="ip" type="xsd:string" />
						<xsd:attribute name="port" type="xsd:string" />
						<xsd:attribute name="username" type="xsd:string" />
						<xsd:attribute name="password" type="xsd:string" />
						<xsd:attribute name="dbname" type="xsd:string" />
						<xsd:attribute name="dialect" type="xsd:string" />
						<xsd:attribute name="initSize" type="xsd:string" />
						<xsd:attribute name="maxActive" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
				<xsd:element name="NoSqlDB">
					<xsd:complexType>
						<xsd:sequence></xsd:sequence>
						<xsd:attribute name="ip" type="xsd:string" />
						<xsd:attribute name="port" type="xsd:string" />
						<xsd:attribute name="dbname" type="xsd:string" />
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== FutureElement/FEEP/src/main/webapp/FEEP.xml
<?xml version="1.0" encoding="UTF-8"?>
<FEEP xmlns="http://www.feep.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
	xsi:schemaLocation="http://www.feep.com/schema http://www.feep.com/Feep-1.0.xsd">
	<!-- 初始化常量 -->
	<Constant>
        <Title>FEEP开发平台</Title>
		<!-- 上下文路径 -->
		<ContextPath>FEEP</ContextPath>
		<!-- 定义是否开发模式 -->
		<DevMode>true</DevMode>
		<!-- 定义文件模板库 路径 -->
		<Temp>template</Temp>
		<!-- 默认分页页数 -->
		<DefaultPageSize>20</DefaultPageSize>
		<!-- 是否加载用户到缓存 -->
		<AddUserToCache>true</AddUserToCache>
	</Constant>
	<!-- 文件上传配置 -->
	<FileUpload uploadPath="../uploadFiles" maxUploadSize="157286400"
		maxInMemorySize="4096" />
	<!-- 定义缺省数据源 dialect: oracle, postgresql, mysql, sqlserver -->
	<DataSource dbname="feep" ip="localhost" port="5432"
		username="postgres" password="123456" dialect="postgresql" initSize="3"
		maxActive="20" />
</FEEP>
