=== FutureElement/FEEP/src/main/resources/FeepResource/scheme/Feep-MAPPING-1.0.xsd
<?xml version="1.0" encoding= "UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	xmlns="http://www.feep.com/schema" targetNamespace="http://www.feep.com/schema"
	elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xsd:element name="FEEP-MAPPING">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="SQL" minOccurs="1" maxOccurs="unbounded">
					<xsd:complexType>
						<xsd:simpleContent>
							<xsd:extension base="xsd:string">
								<xsd:attribute name="key" type="xsd:string" />
							</xsd:extension>
						</xsd:simpleContent>
					</xsd:complexType>
				</xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
</xsd:schema>

=== FutureElement/FEEP/src/main/resources/FeepResource/sql/dbms/ModuleFieldDap.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FEEP-MAPPING xmlns="http://www.feep.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.feep.com/schema http://www.feep.com/Feep-MAPPING-1.0.xsd">
    <SQL key="sql.dbms.moduleField.addModuleField">INSERT INTO feep_modulefield (id, name, showname, code, sort, searchable, moduleid, tablefieldid) VALUES (?, ?, ?, ?, ?, ?, ?, ?)</SQL>
    <SQL key="sql.dbms.moduleField.deleteModuleFieldById">DELETE FROM feep_modulefield WHERE id = ?</SQL>
    <SQL key="sql.dbms.moduleField.deleteModuleFieldByIds">DELETE FROM feep_modulefield WHERE id in</SQL>
    <SQL key="sql.dbms.moduleField.deleteModuleFieldByModuleId">DELETE FROM feep_modulefield WHERE moduleid = ?</SQL>
    <SQL key="sql.dbms.moduleField.updateModuleField">UPDATE feep_modulefield SET name = ?,showname = ?,code = ?,sort = ?, searchable = ?,moduleid = ?,tablefieldid = ? WHERE id = ?</SQL>
    <SQL key="sql.dbms.moduleField.findModuleFieldsByModuleId">SELECT id, name, showname, code, sort, searchable, moduleid, tablefieldid FROM feep_modulefield WHERE moduleid = ?</SQL>
    <SQL key="sql.dbms.moduleField.findModuleFieldById">SELECT id, name, showname, code, sort, searchable, moduleid, tablefieldid FROM feep_modulefield WHERE id = ?</SQL>
    <SQL key="sql.dbms.moduleField.findAll">SELECT id, name, showname, code, sort, searchable, moduleid, tablefieldid FROM feep_modulefield</SQL>
</FEEP-MAPPING>

=== FutureElement/FEEP/src/main/resources/FeepResource/sql/dbms/DictionaryItemDao.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FEEP-MAPPING xmlns="http://www.feep.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.feep.com/schema http://www.feep.com/Feep-MAPPING-1.0.xsd">
    <SQL key="sql.dbms.dictionaryItem.addItem">INSERT INTO feep_dictionaryitem(id, codeid, codevalue, sortnum, description, dictionaryid, childrenid) VALUES (?, ?, ?, ?, ?, ?, ?)</SQL>
    <SQL key="sql.dbms.dictionaryItem.deleteItemById">DELETE FROM feep_dictionaryitem WHERE id = ?</SQL>
    <SQL key="sql.dbms.dictionaryItem.deleteItemByIds">DELETE FROM feep_dictionaryitem WHERE id in</SQL>
    <SQL key="sql.dbms.dictionaryItem.deleteItemByDictionaryId">DELETE FROM feep_dictionaryitem WHERE dictionaryid = ?</SQL>
    <SQL key="sql.dbms.dictionaryItem.udpateItemInfo">UPDATE feep_dictionaryitem SET codeid=?, codevalue=?, sortnum=?, description=?, dictionaryid=?, childrenid=? WHERE id = ?</SQL>
    <SQL key="sql.dbms.dictionaryItem.findDictionaryItemById">SELECT id, codeid, codevalue, sortnum, description, dictionaryid, childrenid FROM feep_dictionaryitem WHERE id = ?</SQL>
    <SQL key="sql.dbms.dictionaryItem.findDictionaryChildrenItemsById">
        SELECT
            childrenItem.id,
            childrenItem.codeid,
            childrenItem.codevalue,
            childrenItem.sortnum,
            childrenItem.description,
            childrenItem.dictionaryid,
            childrenItem.childrenid
        FROM
            (
                SELECT
                    id,
                    codeid,
                    codevalue,
                    sortnum,
                    description,
                    dictionaryid,
                    childrenid
                FROM
                    feep_dictionaryitem oneitem
                WHERE id = ?
        ) feep_dictionaryitem
        LEFT JOIN feep_dictionaryitem childrenItem ON feep_dictionaryitem.childrenid = childrenItem.dictionaryid
    </SQL>
    <SQL key="sql.dbms.dictionaryItem.findDictionaryItemsByDictionaryId">SELECT id, codeid, codevalue, sortnum, description, dictionaryid, childrenid FROM feep_dictionaryitem WHERE dictionaryid = ?</SQL>
    <SQL key="sql.dbms.dictionaryItem.findAllItems">SELECT id, codeid, codevalue, sortnum, description, dictionaryid, childrenid FROM feep_dictionaryitem</SQL>
</FEEP-MAPPING>

=== FutureElement/FEEP/src/main/resources/FeepResource/sql/system/UserDao.xml
<?xml version="1.0" encoding="UTF-8" ?>
<FEEP-MAPPING xmlns="http://www.feep.com/schema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.feep.com/schema http://www.feep.com/Feep-MAPPING-1.0.xsd">
	<SQL key="sql.common.user.createtable">CREATE TABLE feep_user(id character varying(50) NOT NULL,username character varying(50),showname character varying(50),password character varying(50),type character varying(50),identitycard character varying(50),birthday date,tel character varying(50),email character varying(50),address character varying(100),remarks character varying(200),CONSTRAINT feep_user_pkey PRIMARY KEY (id))</SQL>
	<SQL key="sql.common.user.selectAll">SELECT id, username, password, type, identitycard, birthday, tel, email, address, remarks, showname FROM feep_user</SQL>
	<SQL key="sql.common.user.findById">SELECT id, username, password, type, identitycard, birthday, tel, email, address, remarks, showname FROM feep_user WHERE id = ?</SQL>
	<SQL key="sql.common.user.findByUserName">SELECT id, username, password, type, identitycard, birthday, tel, email, address, remarks, showname FROM feep_user WHERE username = ?</SQL>
	<SQL key="sql.common.user.insertUser">INSERT INTO feep_user(id, username, showname, password, type, identitycard, birthday, tel, email, address, remarks) VALUES (?, ?, ?, ?, ?, ?, ?, ?,?, ?, ?, ?, ?, ?)</SQL>
	<SQL key="sql.common.user.updateUser">UPDATE feep_user SET</SQL>
	<SQL key="sql.common.user.deleteUserById">UPDATE feep_user SET type = '-1' WHERE id = ?</SQL>
	<SQL key="sql.common.user.realDeleteUserById">DELETE FROM feep_user WHERE id = ?</SQL>
	<SQL key="sql.common.user.deleteUserByIds">UPDATE feep_user SET type = '-1' WHERE id in</SQL>
	<SQL key="sql.common.user.realDeleteUserByIds">DELETE FROM feep_user WHERE id in</SQL>
</FEEP-MAPPING>
